# Generated by Django 5.1.1 on 2024-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('publication_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('pages_number', models.IntegerField()),
                ('isbn_10', models.CharField(max_length=10)),
                ('isbn_13', models.CharField(max_length=14)),
                ('read', models.ManyToManyField(blank=True, related_name='read', to='users.user')),
            ],
        ),
    ]
