# Generated by Django 5.1.1 on 2024-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('watched', models.ManyToManyField(blank=True, related_name='watched', to='users.user')),
            ],
        ),
    ]
